# Generate the per-location documentation: for every entry in docs/locations.jl,
# render the three climatology figures into docs/src/assets/<slug>/ (standard,
# location-free names) and write a docs/src/cities/<slug>.md page from one shared
# template. The navigation in docs/make.jl is built from the same list, so adding
# a location there is all it takes.
#
#     julia --project=docs docs/make_locations.jl
#
# Figures are drawn from cached / bundled data only (offline), so the run is
# deterministic and quota-free; a location whose CMIP6 ensemble is only partly
# cached is rendered with the models on hand, one with none has its figures
# skipped and its page says so. Refresh the underlying data first with
# scripts/generate_fixtures.jl + scripts/collect_fixtures.jl.

ENV["CLIMSTATS_OFFLINE"] = "1"
using ClimStats
using CairoMakie

include(joinpath(@__DIR__, "locations.jl"))

const ASSETS = joinpath(@__DIR__, "src", "assets")
const PAGES  = joinpath(@__DIR__, "src", "cities")

# (figure basename, builder given place+models, caption) for the three figures.
const FIGURES = [
    ("today_vs_climate",    (p, m) -> climate_day_comparison(p; models = m), "today vs. day-of-year climatology"),
    ("monthly_climatology", (p, m) -> climate_monthly(p; models = m),        "monthly seasonal cycle"),
    ("daily_climatology",   (p, m) -> climate_daily(p; models = m),          "daily seasonal cycle"),
]

# Projection models with a cached series for `place` (probed offline; an uncached
# model throws and is skipped).
function cached_models(place)
    ms = String[]
    for m in PROJECTION_MODELS
        try
            projection_daily(place; model = m)
            push!(ms, m)
        catch
        end
    end
    return ms
end

# The Markdown page for one location, given which figures were produced.
function page_markdown(place, slug, models, made)
    n, total = length(models), length(PROJECTION_MODELS)
    io = IOBuffer()
    println(io, "# ", place, "\n")
    println(io, "Temperature climatology for **", place, "** — from ",
        "[`climate_day_comparison`](@ref), [`climate_monthly`](@ref) and ",
        "[`climate_daily`](@ref). History is **NASA POWER** (1981→present, keyless ",
        "and quota-free); the future band is a bias-corrected CMIP6 ensemble for ",
        "2041–2050. The series ship as a committed offline fixture (see ",
        "[Caching](../caching.md)), so these figures render with no network and no ",
        "quota. This page is generated by `docs/make_locations.jl`.\n")
    if n == 0
        println(io, "!!! note \"Figures pending\"")
        println(io, "    The CMIP6 projection ensemble for this location has not been ",
            "fetched yet (it was capped by the Open-Meteo hourly quota during fixture ",
            "generation), so the climatology figures — which need the future band — are ",
            "not shown. The NASA POWER history is available: `history_daily(\"", place, "\")`.\n")
    else
        if n < total
            println(io, "!!! note \"Partial CMIP6 ensemble\"")
            println(io, "    The 2041–2050 band uses **", n, " of ", total,
                "** projection models cached for this location; its spread will widen ",
                "once the rest are fetched.\n")
        end
        for (name, _, caption) in FIGURES
            name in made || continue
            println(io, "![", place, ": ", caption, "](../assets/", slug, "/", name, ".png)\n")
        end
    end
    return String(take!(io))
end

mkpath(PAGES)
for loc in DOC_LOCATIONS
    place, slug = loc.place, loc.slug
    println("=== ", place, " ===")
    dir = joinpath(ASSETS, slug); mkpath(dir)
    models = cached_models(place)
    println("  cached projection models: ", isempty(models) ? "(none)" : join(models, ", "))

    made = String[]
    if !isempty(models)
        for (name, build, _) in FIGURES
            try
                save(joinpath(dir, "$(name).png"), build(place, models))
                push!(made, name); println("  ok   ", name)
            catch err
                println("  skip ", name, "  (", first(split(sprint(showerror, err), '\n')), ")")
            end
        end
    else
        println("  no projection ensemble cached — figures skipped")
    end

    write(joinpath(PAGES, "$(slug).md"), page_markdown(place, slug, models, made))
    println("  page -> src/cities/", slug, ".md")
end

println("\nDone. ", length(DOC_LOCATIONS), " location pages generated.")
