"""
    ClimStats

An API for retrieving and analysing climate data for a single location, from
ERA5 reanalysis (the past) and CMIP6 climate projections (the future).

Quick start
-----------
```julia
using ClimStats
using CairoMakie            # a Makie backend: CairoMakie for files, GLMakie for windows

# One-liner: location string in, figure out.
fig = climate_timeseries("Berlin, Germany"; threshold = 30)
save("berlin_hot_days.png", fig)   # `save` re-exported from Makie

# Or step by step, to compute many things from the same download.
data   = era5_daily("Berlin, Germany")     # daily tmax/tmin/tmean/precip
hot    = days_above(data, 30)              # days/yr with Tmax > 30 °C
frost  = frost_days(data)                  # days/yr with Tmin < 0 °C
warming = annual_mean(data; var = :tmean)  # yearly mean temperature
plot_index(hot)
```

Historical data come from a keyless provider via `history_daily`, which defaults
to **NASA POWER** (`power_daily`; no request quota, 1981→present) and can switch
to the Open-Meteo **ERA5** archive (`era5_daily`; 1940→present) with
`source = :era5`. The CMIP6 ensemble (`projection_daily`) is fetched from the
key-less Open-Meteo climate API; SSP-scenario projections use the NASA
NEX-GDDP-CMIP6 backend (`nexgddp_daily`, `ssp_ensemble`, `climate_ssp`), enabled
by `using NCDatasets`. All are cached on disk on first fetch, and the example
locations ship with a bundled offline fixture cache. Plots are built with Makie
(core); load a backend (`CairoMakie` to save files, `GLMakie`/`WGLMakie` for
interactive use) to render or `save` the returned `Figure`. See also the index
helpers (`days_above`, `frost_days`, `annual_mean`, …), `bias_correct` and
`plot_index`.
"""
module ClimStats

using Dates
using Printf
using Statistics
using DataFrames
using HTTP
using JSON3
using Makie

export Location, ClimateData, geocode, table, variables
export era5_daily, power_daily, history_daily, projection_daily, forecast_daily
export default_stop, PROJECTION_MODELS
export set_offline!, offline_mode
export annual_count, days_above, days_below, annual_mean, annual_sum, linear_trend
export daily_climatology, monthly_climatology, monthly_means
export hot_days, summer_days, frost_days, icing_days, tropical_nights, wet_days
export BiasCorrection, QuantileCorrection, AbstractBiasCorrection
export fit_bias_correction, apply_bias_correction, bias_correct, DEFAULT_REF
export Ensemble, projection_ensemble, ensemble_summary, ensemble_index
export CurrentYearEstimate, incomplete_final_year, complete_current_year, estimate_current_year
export plot_index, plot_index!, plot_ensemble!, plot_nowcast!, climate_timeseries, climate_projection
export climate_day_comparison, climate_monthly, climate_daily
export save  # re-exported from Makie; load a backend (CairoMakie/GLMakie) to render
export SSP_SCENARIOS, NEXGDDP_MODELS, NEXGDDP_DEFAULT_MODELS, nexgddp_model_spec
export scenario_label, nexgddp_daily, ssp_ensemble, climate_ssp

include("types.jl")
include("cache.jl")
include("providers.jl")
include("indices.jl")
include("bias.jl")
include("ensemble.jl")
include("nowcast.jl")
include("plotting.jl")
include("nexgddp.jl")

# Directory of the in-repo bundled fixture cache: committed Arrow series for the
# example locations, generated by `scripts/generate_fixtures.jl`. Laid out as a
# DataManifest datacache pool (`<cachetype>/<hash>/…`).
const FIXTURE_DIR = normpath(joinpath(@__DIR__, "..", "data", "fixtures"))

# Register the bundled fixtures as a DataManifest *read pool*, so the example
# locations resolve straight from disk — offline and quota-free — with no setup.
# Prepended idempotently, preserving any user-set `DATAMANIFEST_DATACACHE_POOLS`.
function _register_fixture_pool()
    isdir(FIXTURE_DIR) || return nothing
    key = "DATAMANIFEST_DATACACHE_POOLS"
    sep = Sys.iswindows() ? ';' : ':'
    existing = get(ENV, key, "")
    parts = isempty(existing) ? String[] : split(existing, sep)
    FIXTURE_DIR in parts && return nothing
    ENV[key] = isempty(existing) ? FIXTURE_DIR : string(FIXTURE_DIR, sep, existing)
    return nothing
end

# Offline mode can be switched on at load time via the environment, so a process
# started with `CLIMSTATS_OFFLINE=1` never touches the network.
function __init__()
    _OFFLINE[] = lowercase(strip(get(ENV, "CLIMSTATS_OFFLINE", ""))) in
                 ("1", "true", "yes", "on")
    _register_fixture_pool()
    return nothing
end

end # module ClimStats
